[package]
name = "rslog"
version = "0.1.0"
edition = "2018"

[dependencies]
log_ori = { package = "log", version = "0.4" }
chrono = { version = "0.4", optional = true }

[features]
datetime = ["chrono"]

[dev-dependencies]
env_logger = "0.10.0"

[[example]]
name = "demo"
path = "examples/demo.rs"